apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://192.168.1.5:3306/ticketdb
    spring.datasource.username=user1
    spring.datasource.password=xxxxxxxx
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
